export const incrementVote = 'INCR'
export const decrementVote = 'DECR'
export const resetVotes = 'RESET'
export const login = 'LOGIN'
export const removeItem = 'REMOVE'
export const submit = 'SUBMIT'
export const restart = 'RESTART'